[build]
  command = "npm install --legacy-peer-deps && NODE_ENV=production astro build && node scripts/postbuild-netlify.js && cp -f netlify/functions/ssr.js .netlify/functions/_astrojs-ssr-adapter.js && test -d dist || exit 1"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 4322
  targetPort = 4322

# Asset caching
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Asset caching for other static files
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# General caching
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# API specific headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=60, stale-while-revalidate=300"
    CDN-Cache-Control = "public, s-maxage=60, stale-while-revalidate=300"

# Debug routes - highest priority
[[redirects]]
  from = "/debug-request"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

[[redirects]]
  from = "/env-debug"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

# Specific API route for cities data - highest priority
[[redirects]]
  from = "/api/cities-data"
  to = "/.netlify/functions/cities-data"
  status = 200
  force = true

# API routes - higher priority
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

# Handle SSR routes for states pages - medium priority
[[redirects]]
  from = "/states/*"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

# For test SSR page
[[redirects]]
  from = "/test-ssr"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

# For search page
[[redirects]]
  from = "/search"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

# For any 404 pages, redirect to the custom 404 page - lowest priority
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 

# For Single Page Application fallbacks - lowest priority 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 
